# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# These tasks establish basic IoT functionality.

- name: Collect CLI args if any
  set_fact: az="az {{ lookup('env','AZ_ARGS') }}"

- name: set edge device name
  set_fact:
    azure_edge_name: >-
      {{ azure_edge_group }}-edge
  when:
    - azure_edge_group is defined

- name: set or use edge deployment name
  set_fact:
    deployment_name: >-
      {{ azure_edge_group }}
  when:
    deployment_name is undefined or deployment_name == ""

- name: create tmp
  tempfile:
    state: directory
    suffix: az_deploy
  register: tmp_deploy

- name: Build deployment manifest
  template:
    src: deployment-manifest.json.j2
    dest: "{{ tmp_deploy.path }}/deployment-manifest.json"
    backup: false
  when: not ansible_check_mode

- name: List existing deployment to the edge device
  command: >
    {{ az }} iot edge deployment show
    --deployment-id {{ deployment_name }}
    --hub-name {{ azure_iot_hub_name }}
  register: edge_deployment_show
  ignore_errors: true
  when:
    - azure_iot_hub_name is defined
    - deployment_name is defined

- name: Create a deployment to the edge device (one device)
  command: >
    {{ az }} iot edge deployment create
    --deployment-id {{ deployment_name }}
    --hub-name {{ azure_iot_hub_name }}
    --content {{ tmp_deploy.path }}/deployment-manifest.json
    --target-condition "tags.azure_edge_group='{{ azure_edge_group }}'"
  register: edge_deployment_create
  when:
    - edge_deployment_show.changed and edge_deployment_show.rc != 0
    - azure_iot_hub_name is defined
    - deployment_name == azure_edge_group
  tags:
    - skip_ansible_lint

- name: Create a deployment to the edge device (mass devices)
  command: >
    {{ az }} iot edge deployment create
    --deployment-id {{ deployment_name }}
    --hub-name {{ azure_iot_hub_name }}
    --content {{ tmp_deploy.path }}/deployment-manifest.json
    --target-condition "tags.{{ auto_edge_tag }}=true"
  register: edge_deployment_create
  when:
    - edge_deployment_show.changed and edge_deployment_show.rc != 0
    - azure_iot_hub_name is defined
    - deployment_name != azure_edge_group
  tags:
    - skip_ansible_lint

- name: Clear deployment name for next pass (if not supplied)
  set_fact:
    deployment_name: ""
  when: deployment_name == azure_edge_group
