# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# These tasks establish basic IoT functionality.

- name: Collect CLI args if any
  set_fact: az="az {{ lookup('env','AZ_ARGS') }}"

- name: set edge device name
  set_fact:
    azure_edge_name: >-
      {{ azure_edge_group }}-edge
  when:
    - azure_edge_group is defined

- name: create tmp
  tempfile:
    state: directory
    suffix: az_deploy
  register: tmp_deploy

- name: Build deployment manifest
  template:
    src: deployment-manifest.json.j2
    dest: "{{ tmp_deploy.path }}/deployment-manifest.json"
    backup: false
  when: not ansible_check_mode

- name: Deploy configuration to edge device
  command: >
    {{ az }} iot hub apply-configuration
    --device-id {{ azure_edge_name }}
    --hub-name {{ azure_iot_hub_name }}
    --content {{ tmp_deploy.path }}/deployment-manifest.json
  register: apply_configuration_device
  when:
    - azure_iot_hub_name is defined
