# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# These tasks establish basic IoT functionality.

- name: Collect CLI args if any
  set_fact: az="az {{ lookup('env','AZ_ARGS') }}"

- name: show hub to create
  debug:
    msg: "Creating IoT hub '{{ azure_iot_hub_name }}'."

- name: Just-in-time Azure CLI install for MacOSX
  command: brew install azure-cli
  when: ansible_distribution == "MacOSX"

- name: List Azure CLI extensions
  command: >
    {{ az }} extension list
  register: az_extensions
  when: azure_cli_tenant_id is defined

- name: Add Azure CLI iot extensions
  command: >
    {{ az }} extension add --name azure-cli-iot-ext
  when:
    - az_extensions is defined
    - "'azure-cli-iot-ext' not in az_extensions.stdout"

- name: validate Azure tenant
  command: >
    {{ az }} account show --query 'tenantId' -o tsv
  register: show_tenant
  ignore_errors: true
  when: azure_cli_tenant_id is defined

- name: Perform Azure login
  command: >
    {{ az }} login --service-principal
    -u {{ azure_cli_application_id }} -p {{ azure_cli_application_key }}
    --tenant {{ azure_cli_tenant_id }}
  when:
    - not ansible_check_mode
    - show_tenant.rc != 0

- name: create Azure resource group
  command: >
    {{ az }} group create
    --name {{ azure_iot_group }}
    --location {{ azure_iot_location }}
  when: azure_iot_group is defined

- name: create Azure hub in the resource group
  command: >
    {{ az }} iot hub create
    --resource-group {{ azure_iot_group }}
    --name {{ azure_iot_hub_name }}
    --sku {{ azure_iot_hub_sku }}
  when:
    - azure_iot_group is defined
    - azure_iot_hub_name is defined

- name: create Edge Device attached to the hub
  command: >
    {{ az }} iot device create
    --device-id {{ azure_iot_hub_name }}-edge
    --hub-name {{ azure_iot_hub_name }}
    --resource-group {{ azure_iot_group }}
  when:
    - azure_iot_group is defined
    - azure_iot_hub_name is defined
