# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# These tasks establish basic IoT functionality.

- name: show hub to install
  debug:
    msg: "Creating IoT hub 'hub'."
