# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# These tasks establish basic IoT functionality.

- name: Collect CLI args if any
  set_fact: az="az {{ lookup('env','AZ_ARGS') }}"

- name: show hub to create
  debug:
    msg: "Creating/refreshing IoT hub '{{ azure_iot_hub_name }}'."

- name: Check for Azure CLI install for MacOSX
  command: brew info azure-cli
  when: ansible_distribution == "MacOSX"
  register: osx_azure_cli
  ignore_errors: true

- name: Just-in-time Azure CLI install for MacOSX
  command: brew install azure-cli
  when:
    - ansible_distribution == "MacOSX"
    - not ansible_check_mode
    - osx_azure_cli.rc != 0

- name: List Azure CLI extensions
  command: >
    {{ az }} extension list
  register: az_extensions
  when: azure_cli_tenant_id is defined

- name: Add Azure CLI iot extensions
  command: >
    {{ az }} extension add --name azure-cli-iot-ext
  when:
    - az_extensions is defined and 'skipped' not in az_extensions
    - "'azure-cli-iot-ext' not in az_extensions.stdout"

- name: validate Azure tenant
  command: >
    {{ az }} account show --query 'tenantId'
  register: show_tenant
  ignore_errors: true
  when: azure_cli_tenant_id is defined

- name: Perform Azure login
  command: >
    {{ az }} login --service-principal
    -u {{ azure_cli_application_id }} -p {{ azure_cli_application_key }}
    --tenant {{ azure_cli_tenant_id }}
  when:
    - not ansible_check_mode
    - show_tenant.rc != 0

- name: create Azure resource group
  command: >
    {{ az }} group create
    --name {{ azure_iot_group }}
    --location {{ azure_iot_location }}
  when: azure_iot_group is defined

- name: list Azure iot hubs
  command: >
    {{ az }} iot hub list
  when:
    - azure_iot_hub_name is defined
  register: azure_iot_hubs

- name: set azure_iot_hubs list
  set_fact:
    azure_iot_hub_list: >-
      {{ azure_iot_hubs.stdout | from_json | json_query('[*].name') }}
  when: azure_iot_hubs.changed
  tags:
    - skip_ansible_lint

- name: debug iot hubs
  debug: var=azure_iot_hub_list

- name: create Azure hub in the resource group
  command: >
    {{ az }} iot hub create
    --resource-group {{ azure_iot_group }}
    --name {{ azure_iot_hub_name }}
    --sku {{ azure_iot_hub_sku }}
  when:
    - azure_iot_group is defined
    - azure_iot_hub_name is defined
    - azure_iot_hub_list is defined
    - azure_iot_hub_name not in azure_iot_hub_list

- name: list Azure iot devices at the hub
  command: >
    {{ az }} iot hub device-identity list --hub-name {{ azure_iot_hub_name }}
  when:
    - azure_iot_hub_name is defined
  register: azure_iot_hub_devices

- name: set azure_iot_hub_devices list
  set_fact:
    azure_iot_hub_device_list: >-
      {{ azure_iot_hub_devices.stdout |
      from_json | json_query('[*].deviceId') }}
  when: azure_iot_hub_devices.changed
  tags:
    - skip_ansible_lint

- name: clear groups metadata
  set_fact:
    azure_groups: {}

# Create an iot device for all in the desired range.
- name: Create our mass of device identities
  include_tasks: azure-device.yml
  with_sequence: start=1 end={{ azure_device_count }}
  loop_control:
    loop_var: device_index
  when: azure_device_count is defined

# Create an edge device for each provided name.
- include_tasks: azure-edge-device.yml
  with_items: "{{ azure_iot_edge_names }}"
  loop_control:
    loop_var: azure_edge_group
